server.port=8084

spring.application.name=order-service
spring.datasource.url=jdbc:sqlite:./data/order.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

service.cart.url=http://localhost:8083
service.catalog.url=http://localhost:8082
service.payment.url=http://localhost:8085
